/* Verses shown under the pictures.
 * Source: Qur'an verses on good character (77 ayat), filtered to those
 * that read well under a photo. Translation: Saheeh International.
 * Edit freely — each entry is { text, ref }. */
window.PF_QUOTES = [
  { text: "Do you order righteousness of the people and forget yourselves while you recite the Scripture? Then will you not reason?",
    ref: "Surah Al-Baqarah 2:44" },
  { text: "And of the people is he who sells himself, seeking means to the approval of Allah. And Allah is kind to [His] servants.",
    ref: "Surah Al-Baqarah 2:207" },
  { text: "But as for those who believed and did righteous deeds, He will give them in full their rewards, and Allah does not like the wrongdoers.",
    ref: "Surah Al-Imran 3:57" },
  { text: "And let there be [arising] from you a nation inviting to [all that is] good, enjoining what is right and forbidding what is wrong, and those will be the successful.",
    ref: "Surah Al-Imran 3:104" },
  { text: "And hasten to forgiveness from your Lord and a garden as wide as the heavens and earth, prepared for the righteous",
    ref: "Surah Al-Imran 3:133" },
  { text: "Who spend [in the cause of Allah] during ease and hardship and who restrain anger and who pardon the people - and Allah loves the doers of good;",
    ref: "Surah Al-Imran 3:134" },
  { text: "So is one who pursues the pleasure of Allah like one who brings upon himself the anger of Allah and whose refuge is Hell? And wretched is the destination.",
    ref: "Surah Al-Imran 3:162" },
  { text: "And when you are greeted with a greeting, greet [in return] with one better than it or [at least] return it [in a like manner]. Indeed, Allah is ever, over all things, an Accountant.",
    ref: "Surah An-Nisa 4:86" },
  { text: "And if they incline to peace, then incline to it [also] and rely upon Allah. Indeed, it is He who is the Hearing, the Knowing.",
    ref: "Surah Al-Anfal 8:61" },
  { text: "And when Joseph reached maturity, We gave him judgment and knowledge. And thus We reward the doers of good.",
    ref: "Surah Yusuf 12:22" },
  { text: "Indeed, this Qur'an guides to that which is most suitable and gives good tidings to the believers who do righteous deeds that they will have a great reward.",
    ref: "Surah Al-Isra 17:9" },
  { text: "And give the relative his right, and [also] the poor and the traveler, and do not spend wastefully.",
    ref: "Surah Al-Isra 17:26" },
  { text: "And if you [must] turn away from the needy awaiting mercy from your Lord which you expect, then speak to them a gentle word.",
    ref: "Surah Al-Isra 17:28" },
  { text: "And speak to him with gentle speech that perhaps he may be reminded or fear [Allah].\"",
    ref: "Surah Ta-Ha 20:44" },
  { text: "And they who turn away from ill speech",
    ref: "Surah Al-Mu'minun 23:3" },
  { text: "And they who are to their trusts and their promises attentive",
    ref: "Surah Al-Mu'minun 23:8" },
  { text: "And those who accuse chaste women and then do not produce four witnesses - lash them with eighty lashes and do not accept from them testimony ever after. And those are the defiantly disobedient,",
    ref: "Surah An-Nur 24:4" },
  { text: "Why, when you heard it, did not the believing men and believing women think good of one another and say, \"This is an obvious falsehood\"?",
    ref: "Surah An-Nur 24:12" },
  { text: "When you received it with your tongues and said with your mouths that of which you had no knowledge and thought it was insignificant while it was, in the sight of Allah, tremendous.",
    ref: "Surah An-Nur 24:15" },
  { text: "O you who have believed, do not enter houses other than your own houses until you ascertain welcome and greet their inhabitants. That is best for you; perhaps you will be reminded.",
    ref: "Surah An-Nur 24:27" },
  { text: "Tell the believing men to reduce [some] of their vision and guard their private parts. That is purer for them. Indeed, Allah is Acquainted with what they do.",
    ref: "Surah An-Nur 24:30" },
  { text: "And when the children among you reach puberty, let them ask permission [at all times] as those before them have done. Thus does Allah make clear to you His verses; and Allah is Knowing and Wise.",
    ref: "Surah An-Nur 24:59" },
  { text: "And the servants of the Most Merciful are those who walk upon the earth easily, and when the ignorant address them [harshly], they say [words of] peace,",
    ref: "Surah Al-Furqan 25:63" },
  { text: "And [they are] those who, when they spend, do so not excessively or sparingly but are ever, between that, [justly] moderate",
    ref: "Surah Al-Furqan 25:67" },
  { text: "And do not turn your cheek [in contempt] toward people and do not walk through the earth exultantly. Indeed, Allah does not like everyone self-deluded and boastful.",
    ref: "Surah Luqman 31:18" },
  { text: "And be moderate in your pace and lower your voice; indeed, the most disagreeable of sounds is the voice of donkeys.\"",
    ref: "Surah Luqman 31:19" },
  { text: "And those who harm believing men and believing women for [something] other than what they have earned have certainly born upon themselves a slander and manifest sin.",
    ref: "Surah Al-Ahzab 33:58" },
  { text: "And not equal are the good deed and the bad. Repel [evil] by that [deed] which is better; and thereupon the one whom between you and him is enmity [will become] as though he was a devoted friend.",
    ref: "Surah Fussilat 41:34" },
  { text: "Indeed, those who lower their voices before the Messenger of Allah - they are the ones whose hearts Allah has tested for righteousness. For them is forgiveness and great reward.",
    ref: "Surah Al-Hujurat 49:3" },
  { text: "O you who have believed, if there comes to you a disobedient one with information, investigate, lest you harm a people out of ignorance and become, over what you have done, regretful.",
    ref: "Surah Al-Hujurat 49:6" },
  { text: "When they entered upon him and said, \"[We greet you with] peace.\" He answered, \"[And upon you] peace, [you are] a people unknown.",
    ref: "Surah Adh-Dhariyat 51:25" },
  { text: "It is He who has sent among the unlettered a Messenger from themselves reciting to them His verses and purifying them and teaching them the Book and wisdom - although they were before in clear error -",
    ref: "Surah Al-Jumu'ah 62:2" },
  { text: "And indeed, you are of a great moral character.",
    ref: "Surah Al-Qalam 68:4" },
];
